// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.4
// source: protobufs/hackernews.proto

package protobufs

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TypeRequest_Type int32

const (
	TypeRequest_JOB   TypeRequest_Type = 0
	TypeRequest_STORY TypeRequest_Type = 1
)

// Enum value maps for TypeRequest_Type.
var (
	TypeRequest_Type_name = map[int32]string{
		0: "JOB",
		1: "STORY",
	}
	TypeRequest_Type_value = map[string]int32{
		"JOB":   0,
		"STORY": 1,
	}
)

func (x TypeRequest_Type) Enum() *TypeRequest_Type {
	p := new(TypeRequest_Type)
	*p = x
	return p
}

func (x TypeRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_protobufs_hackernews_proto_enumTypes[0].Descriptor()
}

func (TypeRequest_Type) Type() protoreflect.EnumType {
	return &file_protobufs_hackernews_proto_enumTypes[0]
}

func (x TypeRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeRequest_Type.Descriptor instead.
func (TypeRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_protobufs_hackernews_proto_rawDescGZIP(), []int{0, 0}
}

type TypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type TypeRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=hackernews.TypeRequest_Type" json:"type,omitempty"`
}

func (x *TypeRequest) Reset() {
	*x = TypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_hackernews_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeRequest) ProtoMessage() {}

func (x *TypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_hackernews_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeRequest.ProtoReflect.Descriptor instead.
func (*TypeRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_hackernews_proto_rawDescGZIP(), []int{0}
}

func (x *TypeRequest) GetType() TypeRequest_Type {
	if x != nil {
		return x.Type
	}
	return TypeRequest_JOB
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type      string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title     string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content   string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Url       string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Score     int32  `protobuf:"zigzag32,6,opt,name=score,proto3" json:"score,omitempty"`
	CreatedBy string `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt int64  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_hackernews_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_hackernews_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_protobufs_hackernews_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Item) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Item) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Item) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Item) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_protobufs_hackernews_proto protoreflect.FileDescriptor

var file_protobufs_hackernews_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x68, 0x61, 0x63, 0x6b,
	0x65, 0x72, 0x6e, 0x65, 0x77, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x68, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x77, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x68, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x77, 0x73, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x1a, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07,
	0x0a, 0x03, 0x4a, 0x4f, 0x42, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x4f, 0x52, 0x59,
	0x10, 0x01, 0x22, 0xc0, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x11,
	0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0x79, 0x0a, 0x03, 0x41, 0x50, 0x49, 0x12, 0x37, 0x0a, 0x07,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x10, 0x2e, 0x68, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x77, 0x73, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x22, 0x00, 0x30, 0x01, 0x12, 0x39, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x17, 0x2e, 0x68, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x77, 0x73, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x68, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x6e, 0x65, 0x77, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c,
	0x75, 0x73, 0x68, 0x63, 0x2f, 0x68, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2d, 0x6e, 0x65, 0x77, 0x73,
	0x2d, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobufs_hackernews_proto_rawDescOnce sync.Once
	file_protobufs_hackernews_proto_rawDescData = file_protobufs_hackernews_proto_rawDesc
)

func file_protobufs_hackernews_proto_rawDescGZIP() []byte {
	file_protobufs_hackernews_proto_rawDescOnce.Do(func() {
		file_protobufs_hackernews_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufs_hackernews_proto_rawDescData)
	})
	return file_protobufs_hackernews_proto_rawDescData
}

var file_protobufs_hackernews_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobufs_hackernews_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobufs_hackernews_proto_goTypes = []interface{}{
	(TypeRequest_Type)(0), // 0: hackernews.TypeRequest.Type
	(*TypeRequest)(nil),   // 1: hackernews.TypeRequest
	(*Item)(nil),          // 2: hackernews.Item
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_protobufs_hackernews_proto_depIdxs = []int32{
	0, // 0: hackernews.TypeRequest.type:type_name -> hackernews.TypeRequest.Type
	3, // 1: hackernews.API.ListAll:input_type -> google.protobuf.Empty
	1, // 2: hackernews.API.ListType:input_type -> hackernews.TypeRequest
	2, // 3: hackernews.API.ListAll:output_type -> hackernews.Item
	2, // 4: hackernews.API.ListType:output_type -> hackernews.Item
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobufs_hackernews_proto_init() }
func file_protobufs_hackernews_proto_init() {
	if File_protobufs_hackernews_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobufs_hackernews_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_hackernews_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufs_hackernews_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobufs_hackernews_proto_goTypes,
		DependencyIndexes: file_protobufs_hackernews_proto_depIdxs,
		EnumInfos:         file_protobufs_hackernews_proto_enumTypes,
		MessageInfos:      file_protobufs_hackernews_proto_msgTypes,
	}.Build()
	File_protobufs_hackernews_proto = out.File
	file_protobufs_hackernews_proto_rawDesc = nil
	file_protobufs_hackernews_proto_goTypes = nil
	file_protobufs_hackernews_proto_depIdxs = nil
}
