// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIClient interface {
	ListAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (API_ListAllClient, error)
	ListType(ctx context.Context, in *TypeRequest, opts ...grpc.CallOption) (API_ListTypeClient, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) ListAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (API_ListAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[0], "/hackernews.API/ListAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIListAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_ListAllClient interface {
	Recv() (*Item, error)
	grpc.ClientStream
}

type aPIListAllClient struct {
	grpc.ClientStream
}

func (x *aPIListAllClient) Recv() (*Item, error) {
	m := new(Item)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) ListType(ctx context.Context, in *TypeRequest, opts ...grpc.CallOption) (API_ListTypeClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[1], "/hackernews.API/ListType", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIListTypeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_ListTypeClient interface {
	Recv() (*Item, error)
	grpc.ClientStream
}

type aPIListTypeClient struct {
	grpc.ClientStream
}

func (x *aPIListTypeClient) Recv() (*Item, error) {
	m := new(Item)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// APIServer is the server API for API service.
// All implementations must embed UnimplementedAPIServer
// for forward compatibility
type APIServer interface {
	ListAll(*emptypb.Empty, API_ListAllServer) error
	ListType(*TypeRequest, API_ListTypeServer) error
	mustEmbedUnimplementedAPIServer()
}

// UnimplementedAPIServer must be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (UnimplementedAPIServer) ListAll(*emptypb.Empty, API_ListAllServer) error {
	return status.Errorf(codes.Unimplemented, "method ListAll not implemented")
}
func (UnimplementedAPIServer) ListType(*TypeRequest, API_ListTypeServer) error {
	return status.Errorf(codes.Unimplemented, "method ListType not implemented")
}
func (UnimplementedAPIServer) mustEmbedUnimplementedAPIServer() {}

// UnsafeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServer will
// result in compilation errors.
type UnsafeAPIServer interface {
	mustEmbedUnimplementedAPIServer()
}

func RegisterAPIServer(s grpc.ServiceRegistrar, srv APIServer) {
	s.RegisterService(&API_ServiceDesc, srv)
}

func _API_ListAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).ListAll(m, &aPIListAllServer{stream})
}

type API_ListAllServer interface {
	Send(*Item) error
	grpc.ServerStream
}

type aPIListAllServer struct {
	grpc.ServerStream
}

func (x *aPIListAllServer) Send(m *Item) error {
	return x.ServerStream.SendMsg(m)
}

func _API_ListType_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TypeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).ListType(m, &aPIListTypeServer{stream})
}

type API_ListTypeServer interface {
	Send(*Item) error
	grpc.ServerStream
}

type aPIListTypeServer struct {
	grpc.ServerStream
}

func (x *aPIListTypeServer) Send(m *Item) error {
	return x.ServerStream.SendMsg(m)
}

// API_ServiceDesc is the grpc.ServiceDesc for API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hackernews.API",
	HandlerType: (*APIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListAll",
			Handler:       _API_ListAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListType",
			Handler:       _API_ListType_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobufs/hackernews.proto",
}
